# Generated by Django 4.2 on 2023-04-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='user_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='register',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
