# Generated by Django 4.2 on 2023-05-10 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_register_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='hamper_id',
        ),
        migrations.AddField(
            model_name='order',
            name='hamper_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.hamper'),
        ),
    ]
