# Generated by Django 4.2 on 2023-05-16 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_cart_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hamper',
            name='category_id',
        ),
    ]
